<?php
/**
 * @file
 * Provides a Views plugin for displaying images in a Mosaic Grid layout.
 */

/**
 * Implements hook_autoload_info().
 */
function mosaic_grid_autoload_info() {
  return array(
    'views_plugin_style_mosaic_grid' => 'views_plugin_style_mosaic_grid.inc',
  );
}

/**
 * Load include file.
 */
module_load_include('inc', 'mosaic_grid', 'mosaic_grid.views');

/**
 * Implements hook_views_api().
 */
function mosaic_grid_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'mosaic_grid'),
    'template_path' => backdrop_get_path('module', 'mosaic_grid'),
  );
}

/**
 * Implements hook_library_info().
 */
function mosaic_grid_library_info() {
  $libraries['flexImages'] = array(
    'title' => 'Flex Images',
    'website' => 'https://goodies.pixabay.com/jquery/flex-images/demo.html',
    'version' => '1.0.4',
    'js' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.flex-images.min.js' => array(
        'weight' => 1,
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.flex-images.css' => array(),
    ),
  );

  $libraries['lazyloadxt'] = array(
    'title' => 'Lazy Load XT',
    'website' => 'http://ressio.github.io/lazy-load-xt/',
    'version' => '1.1.0',
    'js' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.lazyloadxt.min.js' => array(
        'weight' => 2,
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.lazyloadxt.fadein.min.css' => array(),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function mosaic_grid_menu() {
  $items['admin/config/media/mosaic_grid'] = array(
    'title' => 'Mosaic Grid',
    'description' => 'Configure global options for Mosaic Grid views formatter.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mosaic_grid_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'mosaic_grid.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_config_info().
 */
function mosaic_grid_config_info() {
  return array(
    'mosaic_grid.settings' => array(
      'label' => t('Mosaic Grid settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_views_pre_render().
 * Displays warning about styles in preview mode.
}*/
function mosaic_grid_views_pre_render(&$view) {
  if ($view->preview) {
    $options = $view->style_plugin->options;
    if (!empty($options['captions']['source'])) {
      // Get deafault and views theme names.
      $default_theme_name = config_get('system.core', 'theme_default');
      $views_theme_name = config_get('views_ui.settings', 'custom_theme');
      if ($views_theme_name == '_default')
        $views_theme_name = config_get('system.core', 'admin_theme');
      // Show warning if views and default themes are not the same.
      if ($views_theme_name != $default_theme_name) {
        $themes = list_themes();
        $views_human_name = $themes[$views_theme_name]->info['name'];
        $default_human_name = $themes[$default_theme_name]->info['name'];
        backdrop_set_message(
          t("This preview uses styles from theme %admin. Make sure to check the final look of captions with your site's default theme (%default).", array('%admin' => $views_human_name, '%default' => $default_human_name)),
          'warning'
        );
      }
    }
  }
}

/**
 * Preprocess function for module's template views_view_mosaic-grid.tpl.php.
 * Contains most of the module's logic.
 */
function template_preprocess_views_view_mosaic_grid(&$vars) {

  // Get current view.
  $view = $vars['view'];
  // Get style plugin for this view.
  $style_plugin = $view->style_plugin;
  // Get config and plugin options.
  $config  = config('mosaic_grid.settings');
  $options = $vars['options'];

  // Find names of the image and body fields handlers.
  // These are needed to retrieve fields raw and rendered data.
  $image_field_name = $style_plugin->get_first_non_excluded_image_field()['field_name'];
  $text_field_name  = $style_plugin->get_first_non_excluded_text_field()['field_name'];

  // Get and process all the required data for image display.
  if (isset($image_field_name)) {
    // Set arrays for storing data.
    $items_rendered = array();
    $items_width    = array();
    $items_height   = array();
    $captions = empty($options['captions']['source']) ? NULL : array();

    // Get number of items(rows).
    $rows = count($view->result);

    // Process each item(row).
    for ($i = 0; $i < $rows; $i++) {
      // Get raw image fields value.
      $image_field_value = $style_plugin->get_field_value($i, $image_field_name);
      // Get width and height of an image. It is assumed that image field has
      // one value.
      $width  = $image_field_value[0]['width'];
      $height = $image_field_value[0]['height'];
      // Check that image width and height are not zero.
      // Zero height/width may indicate that image file is missing.
      if ($width > 0 && $height > 0) {
        // Store image dimentions.
        $items_width[$i]  = $width;
        $items_height[$i] = $height;
        // Store rendered image field.
        $items_rendered[$i] = $style_plugin->get_field($i, $image_field_name);

        // If caption source is set then store captions.
        switch ($options['captions']['source']) {
          case 'alt':
            $alt_value = $image_field_value[0]['alt'];
            if (isset($alt_value) && $alt_value != '') {
              $captions[$i] = '<p>' . $alt_value . '</p>';
            }
            break;
          case 'title':
            $title_value = $image_field_value[0]['title'];
            if (!empty($title_value)) {
              $captions[$i] = '<p>' . $title_value . '</p>';
            }
            break;
          case 'text':
            if (isset($text_field_name)) {
              // Get text field as caption.
              $text = $style_plugin->get_field($i, $text_field_name);
              // If text is not html then wrap it in <p> tags. This is required for proper styling.
              if ($text == strip_tags($text)) {
                $text = '<p>' . $text . '</p>';
              }
              $captions[$i] = $text;
            }
            break;
        }
      }
      elseif (empty($options['hide_empty'])) {
        // Fill in values needed for empty image warning display.
        $items_rendered[$i] = FALSE;
        $items_width[$i] = 100;
        $items_height[$i] = 100;
      }
    }
  }
  else {
    // This shouldn't be ever seen by a user as style plugin
    // validation should ensure an image field is added to views.
    backdrop_set_message(t('No image field found.'), 'error');
    return;
  }

  // Create unique id for the mosaic grid.
  $mosaic_id = 'mosaic-grid-' . $view->name . '-' . $view->current_display;

  // Store data in variables to be accessible by the template.
  $vars['items_rendered'] = $items_rendered;
  $vars['captions']       = $captions;
  $vars['width']          = $items_width;
  $vars['height']         = $items_height;
  $vars['mosaic_id']      = $mosaic_id;

  // Create settings array for js.
  $js_settings = array(
    'mosaic_grid' => array(
      'lazyload' => array(
        'edgeY'          => $config->get('lazyload_edgeY'),
      ),
      $mosaic_id => array(
        'max_row_height' => $options['max_row_height'],
        'max_rows'       => $options['max_rows'],
        'truncate'       => $options['truncate'],
      ),
    ),
  );

  // Get module's directory.
  $module_dir = backdrop_get_path('module', 'mosaic_grid');

  // Add flexImages and lazyLoadXt jQuery libraries.
  backdrop_add_library('mosaic_grid', 'flexImages', FALSE);
  backdrop_add_library('mosaic_grid', 'lazyloadxt', FALSE);

  // Add settings and load js to initiate plugins.
  backdrop_add_js($js_settings, 'setting');
  backdrop_add_js($module_dir . '/js/mosaic_grid.js');

  // Load module's styles.
  backdrop_add_css($module_dir . '/css/mosaic_grid.css');

  // Check loader style setting.
  $loader_style = $config->get('loader_style');

  // The rest of the function code below generates customized CSS, based on
  // configuration, and module options.
  $custom_css = '';

  // If one of the loader styles selected then add it's CSS file.
  if (!empty($loader_style)) {
    backdrop_add_css($module_dir . '/css/mosaic_grid_loader_' . $loader_style . '.css');

    // Add color customisation as inline css.
    $color_hex = $config->get('loader_color');
    switch ($loader_style) {
        case 'spinning_ring':
        case 'spinning_ring_thin':
          // Check if color is a valid hex color and convert it to rgb.
          if (Color::validateHex($color_hex)) {
            $color = Color::hexToRgb($color_hex);
          }
          else {
            $color = Color::hexToRgb('#ffffff');
          }
          $custom_css = "
            .mosaic-grid-loader {
              border-color: rgba({$color['red']}, {$color['green']}, {$color['blue']}, 0.2);
              border-left-color: {$color_hex};
            }";
          break;

        case 'floating_balls':
        case 'three_dots':
        case 'square_blocks':
          $custom_css = "
            .mosaic-grid-loader {
              color: {$color_hex};
            }";
          break;

        case 'vertical_blocks':
          $custom_css = "
            .mosaic-grid-loader,
            .mosaic-grid-loader:before,
            .mosaic-grid-loader:after {
              background: {$color_hex};
              color: {$color_hex};
            }";
          break;
      }
    }

  // Set caption height options.
  $height = '';
  switch ($options['captions']['height']['option']) {
    case 'fixed':
      $height .= 'height: ' . $options['captions']['height']['value'] . 'em;';
      // Intentionally no break here. Max-height is needed anyway.
    case 'limit':
      $height .= 'max-height: ' . $options['captions']['height']['value'] . 'em;';
      break;
  }

  // Create style overrides if caption style is set to custom.
  if ($config->get('caption_style_override')) {
    // Get settings for caption style.
    $font_color  = $config->get('caption_font_color');
    $bg_color    = $config->get('caption_background_color');
    $opacity     = $config->get('caption_opacity') / 100;
    $font_size   = $config->get('caption_font_size');
    $padding     = $config->get('caption_padding');
    $padding_h   = $options['captions']['no_padding_h'] ? 0 : $padding * 1.5;

    // Check if background color is a valid hex color and convert it to rgb.
    if (Color::validateHex($bg_color)) {
      $color = Color::hexToRgb($bg_color);
    }
    else {
      $color = Color::hexToRgb('#000000');
    }
    // Create css with inserted values.
    $custom_css .= "
      .mosaic-grid-caption {
        color: {$font_color};
        background: rgba({$color['red']}, {$color['green']}, {$color['blue']}, {$opacity});
        font-size: {$font_size}em;
        {$height}
      }
      .mosaic-grid-caption > * {
        color: {$font_color} !important;
        padding: {$padding}em {$padding_h}em;
      }";
  }
  else {
    if ($options['captions']['no_padding_h']) {
      // Make 'no horisontal padding' work even when no custom caption style set.
      $custom_css .= "
        .mosaic-grid-caption > * {
          padding-left: 0em;
          padding-right: 0em;
        }";
    }
    if ($height != '') {
      $custom_css .= "
        .mosaic-grid-caption {
          {$height}
        }";
    }
  }
  // Minify generated stylesheet and add it to the page.
  if ($custom_css != '') {
    $vars['custom_css'] = backdrop_load_stylesheet_content($custom_css, TRUE);
    backdrop_add_css($vars['custom_css'], array('type' => 'inline'));
  }
}

/**
 * Implements hook_preprocess_image().
 * Prepares images for lazy loading script.
 */
function mosaic_grid_preprocess_image(&$variables) {
  // Check if there is an active view with this style plugin.
  $view = views_get_current_view();
  if (!isset($view)) return;
  if ($view->style_plugin->plugin_name != 'mosaic_grid') return;

  // Check if image lazy loading is enabled in module settings.
  $lazyload = config_get('mosaic_grid.settings', 'lazyload_enabled');
  if (!$lazyload) return;

  // Change src attribute to blank image and assign actual image url to lazy-src.
  // This is required for lazy loading js plugin to work.
  $path_or_uri = $variables['uri'] ? $variables['uri'] : $variables['path'];
  $variables['attributes']['lazy-src'] = file_create_url($path_or_uri);
  $variables['attributes']['src'] = "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";
}
