<?php
/**
 * @file
 * Provides a Views plugin for displaying images in a Mosaic Grid layout.
 */

/**
 * Implements hook_autoload_info().
 */
function mosaic_grid_autoload_info() {
  return array(
    'views_plugin_style_mosaic_grid' => 'views_plugin_style_mosaic_grid.inc',
  );
}

/*
 * Load include file.
 */
module_load_include('inc','mosaic_grid','mosaic_grid.views');

/*
 * Implements hook_views_api().
 */
function mosaic_grid_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'mosaic_grid'),
    'template_path' => backdrop_get_path('module', 'mosaic_grid'),
  );
}

/**
 * Implements hook_library_info().
 */
function mosaic_grid_library_info() {
  $libraries['flexImages'] = array(
    'title' => 'Flex Images',
    'website' => 'https://goodies.pixabay.com/jquery/flex-images/demo.html',
    'version' => '1.0.4',
    'js' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.flex-images.min.js' => array(
        'weight' => 1,
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.flex-images.css' => array(),
    ),
  );
  
  $libraries['lazyloadxt'] = array(
    'title' => 'Lazy Load XT',
    'website' => 'http://ressio.github.io/lazy-load-xt/',
    'version' => '1.1.0',
    'js' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.lazyloadxt.min.js' => array(
        'weight' => 2,
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.lazyloadxt.fadein.min.css' => array(),
    ),
  );
  
  return $libraries;
}

/**
 * Implements hook_menu().
 */
function mosaic_grid_menu() {
  $items['admin/config/media/mosaic_grid'] = array(
    'title' => 'Mosaic Grid',
    'description' => 'Configure global options for Mosaic Grid views formatter.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mosaic_grid_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'mosaic_grid.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_config_info().
 */
function mosaic_grid_config_info() {
  return array(
    'mosaic_grid.settings' => array(
      'label' => t('Mosaic Grid settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Preprocess function for module's template views_view_mosaic-grid.tpl.php.
 * Contains most of the module's logic.
 */
function template_preprocess_views_view_mosaic_grid(&$vars) {

  // Get current view.
  $view = $vars['view'];
  // Get style plugin for this view.
  $style_plugin = $view->style_plugin; 
  // Get config and plugin options.
  $config  = config('mosaic_grid.settings');
  $options = $vars['options'];

  // Find names of the image and body fields handlers.
  // These are needed to retrieve fields raw and rendered data.
  $image_field_name = $style_plugin->get_first_non_excluded_image_field()['field_name'];
  $text_field_name  = $style_plugin->get_first_non_excluded_text_field()['field_name'];

  // Get and process all the required data for image display.
  if (isset($image_field_name)) {
    // Set arrays for storing data.
    $items_rendered = array();
    $items_width    = array();
    $items_height   = array();
    $captions = $options['caption'] != 'none' ? array() : NULL;
    
    // Get number of items(rows).
    $rows = count($view->result);

    // Process each item(row).
    for($i = 0; $i < $rows; $i++) {
      // Get raw image fields value.
      $image_field_value = $style_plugin->get_field_value($i, $image_field_name);
      // Get width and height of an image. 
      // It is assumed that image field has one value.
      $width  = $image_field_value[0]['width'];
      $height = $image_field_value[0]['height'];
      // Check that image width and height are not zero.
      // Zero height/width may indicate that image file is missing.
      if($width > 0 && $height > 0) {
        // Store image dimentions.
        $items_width[$i]  = $width;
        $items_height[$i] = $height;
        // Store rendered image field.
        $items_rendered[$i] = $style_plugin->get_field($i, $image_field_name);
        
        // If caption source is set then store captions.
        switch($options['caption']) {
          case 'node_title':
            $nid = $view->result[$i]->nid;
            $node_title_value = node_load($nid)->title;
            if(!empty($node_title_value)) {
              $captions[$i] = '<p>' . $node_title_value . '</p>';  
            }
            break;
          case 'alt':
            $alt_value = $image_field_value[0]['alt'];
            if(isset($alt_value) && $alt_value != '') {
              $captions[$i] = '<p>' . $alt_value . '</p>';  
            }
            break;
          case 'title':
            $title_value = $image_field_value[0]['title'];
            if(!empty($title_value)) {
              $captions[$i] = '<p>' . $title_value . '</p>';  
            }
            break;
          case 'text':
            if(isset($text_field_name)){
              // Assign rendered text field as caption.
              $captions[$i] = $style_plugin->get_field($i, $text_field_name);
            } 
            break;
        }
      }
      elseif (empty($options['hide_empty'])) {
        // Fill in values needed for empty image warning display.
        $items_rendered[$i] = FALSE;
        $items_width[$i] = 100;
        $items_height[$i] = 100;
      }
    }
  }
  else {
    // This shouldn't be ever seen by a user as style plugin
    // validation should ensure an image field is added to views.
    backdrop_set_message('No image field found.', 'error');
    return;
  }
  
  // Create unique id for the mosaic grid.
  $mosaic_id = 'mosaic-grid-' . $view->name . '-' . $view->current_display;
  
  // Store data in variables to be accessible by the template.
  $vars['items_rendered'] = $items_rendered;
  $vars['captions']       = $captions;
  $vars['width']          = $items_width;
  $vars['height']         = $items_height;
  $vars['mosaic_id']      = $mosaic_id;
  $vars['gap']            = $options['gap'];
 
  // Create settings array for js.
  $js_settings = array (
    'mosaic_grid' => array(
      'lazyload' => array(
        'edgeY'          => $config->get('lazyload_edgeY'),
        'editing'        => $view->editing,
      ),
      $mosaic_id => array (
        'max_row_height' => $options['max_row_height'],
        'max_rows'       => $options['max_rows'],
        'truncate'       => $options['truncate'],
      ),
    ),
  );

  // Get module's directory.
  $module_dir = backdrop_get_path('module', 'mosaic_grid');

  // Add flexImages and lazyLoadXt jQuery libraries.
  backdrop_add_library('mosaic_grid', 'flexImages', FALSE);
  backdrop_add_library('mosaic_grid', 'lazyloadxt', FALSE);
  
  // Add settings and load js to initiate plugins.
  backdrop_add_js($js_settings, 'setting');
  backdrop_add_js($module_dir . '/js/mosaic_grid.js');
  
  // Load module's styles.
  backdrop_add_css($module_dir . '/css/mosaic_grid.css');
  
  // Check loader style setting.
  $loader_style = $config->get('loader_style');
  
  // If one of the loader styles selected then add it's css file.
  if(!empty($loader_style) && $loader_style != 'none'){
    backdrop_add_css($module_dir . '/css/mosaic_grid_loader_' . $loader_style . '.css');
    
    // Add color customisation as inline css.
    $color_hex = $config->get('loader_color');
    $loader_css = false;
    switch($loader_style){
        case 'spinning_ring':
        case 'spinning_ring_thin':
          $color = image_hex2rgba($color_hex);
          $loader_css = <<<"SPIN"
            .mosaic-grid-loader {
              border-color: rgba({$color['red']}, {$color['green']}, {$color['blue']}, 0.2);
              border-left-color: {$color_hex};
            }
SPIN;
          break;

        case 'floating_balls':
        case 'three_dots':
        case 'square_blocks':
          $loader_css = <<<"SPIN"
            .mosaic-grid-loader {
              color: {$color_hex};
            }
SPIN;
          break;
        
        case 'vertical_blocks':
          $loader_css = <<<"SPIN"
            .mosaic-grid-loader,
            .mosaic-grid-loader:before,
            .mosaic-grid-loader:after {
              background: {$color_hex};
              color: {$color_hex};}
SPIN;
          break;
      }
      if($loader_css)
        $loader_css = minify($loader_css);
        backdrop_add_css($loader_css, array('type' => 'inline'));
      $vars['loader_css'] = $loader_css;
    }

  // Create style overrides if caption style is set to custom.
  if($config->get('caption_style_override')){
    // Get settings for caption style.
    $color       = $config->get('caption_font_color');
    $opacity     = $config->get('caption_opacity') / 100;
    $font_size   = $config->get('caption_font_size');
    $padding     = $config->get('caption_padding');
    $padding_hor = (int) ($padding * 1.5);
    // Create css with inserted values.
    $custom_caption_css = <<<"CAP"
      .mosaic-grid-caption {
        color: {$color};
        background: rgba(0, 0, 0, {$opacity});
        font-size: {$font_size}pt;
        padding: {$padding}pt {$padding_hor}pt;
      }
      
      .mosaic-grid-caption > * {
        color: {$color} !important;
      }
CAP;
    // Add the css as inline style sheet.
    $custom_caption_css = minify($custom_caption_css);
    backdrop_add_css($custom_caption_css, array('type' => 'inline'));
    // Store it for template. It will be used for views preview.
    $vars['custom_caption_css'] = $custom_caption_css;
  }
}

/*
 * Removes unnesessary symbols from code string.
 */
function minify($string){
  return str_replace(array(" ", "\r", "\n"), '', $string);
}


/**
 * Implements hook_preprocess_image().
 * Prepares images for lazy loading script.
 */
function mosaic_grid_preprocess_image(&$variables) {
  // Check if there is an active view with this style plugin.
  $view = views_get_current_view();
  if(!isset($view)) return;
  if($view->style_plugin->plugin_name != 'mosaic_grid') return;
  
  // Check if image lazy loading is enabled in module settings.
  $lazyload = config_get('mosaic_grid.settings', 'lazyload_enabled');
  if(!$lazyload) return;
  
  // Change src attribute to blank image and assign actual image url to lazy-src.
  // This is required for lazy loading js plugin to work.
  $path_or_uri = $variables['uri'] ? $variables['uri'] : $variables['path'];
  $variables['attributes']['lazy-src'] = file_create_url($path_or_uri);
  $variables['attributes']['src'] = "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";
}
