<?php

  function time_select_field_info() {
    return array(
      'poutine_maker_poutine' => array(
        'label' => t('Custom Poutine'),
        'description' => t('Custom Poutine Field'),
        'default_widget' => 'poutine_maker_poutine_widget',
        'default_formatter' => 'poutine_maker_poutine_formatter',
      ),
    );
  }

  function time_select_field_widget_info() {
    return array(
      'poutine_maker_poutine_widget' => array(
        'label' => t('Default'),
        'field types' => array('poutine_maker_poutine'),
      ),
    );
  }

  function time_select_field_widget_form(&$form,
                                           &$form_state,
                                           $field,
                                           $instance,
                                           $langcode,
                                           $items,
                                           $delta,
                                           $element) {
    $required = $element['#required'];
    $item =& $items[$delta];

    $element['name'] = array(
      '#title' => t('Name'),
      '#type' => 'textfield',
      '#required' => $required,
      // use #default_value to prepopulate the element
      // with the current saved value
      '#default_value' => isset($item['name']) ? $item['name'] : '',
    );
    $element['vegetarian'] = array(
      '#title' => t('Vegetarian'),
      '#type' => 'checkbox',
      '#default_value' => isset($item['vegetarian']) ? $item['vegetarian'] : '',
    );

    $process = array_merge($fieldset_info['#process'], array('poutine_maker_ignore_parent'));

    $element['meat'] = array(
      '#title' => t('Meat'),
      '#type' => 'fieldset',
      '#process' => $process,
    );

    // Create a checkbox item for each meat on the menu.
    // poutine_maker_toppings_meat() returns an associative array of all the meats I want available
    // (see the example module)
    foreach (poutine_maker_toppings_meat() as $meat_machine=>$meat) {
      $element['meat'][$meat_machine] = array(
        '#title' => t($meat),
        '#type' => 'checkbox',
        '#default_value' => isset($item[$meat_machine]) ? $item[$meat_machine] : '',
      );
    }
  }

  function time_select_field_is_empty($item, $field) {
    $has_stuff = FALSE;

    // first see if any of the topping checkboxes have been checked off
    foreach (poutine_maker_toppings() as $topping_machine=>$topping) {
      if (isset($item[$topping_machine]) && $item[$topping_machine] == 1) {
        $has_stuff = TRUE;
      }
    }

    // has the user checked off the 'vegetarian' checkbox?
    if (isset($item['vegetarian']) && $item['vegetarian'] == 1) {
      $has_stuff = TRUE;
    }

    // has the user entered a name?
    if (!empty($item['name'])) {
      $has_stuff = TRUE;
    }
    return !$has_stuff;
  }
