<?php
/**
 * @file
 * A module that adds one of the ShareThis widget to your website.
 */

/**
 * Implements hook_config_info().
 */
function sharethis_config_info() {
  $prefixes['sharethis.settings'] = array(
    'label' => t('Sharethis settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_autoload_info().
 */
function sharethis_autoload_info() {
  return array(
    'sharethis_handler_field_link' => 'views/sharethis_handler_field_link.inc',
  );
}

/**
 * Implements hook_permission().
 */
function sharethis_permission() {
  return array(
    'administer sharethis' => array(
      'title' => t('Administer ShareThis'),
      'description' => t('Change the settings for how ShareThis behaves on the site.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sharethis_menu() {
  $items['admin/config/services/sharethis'] = array(
    'title' => 'ShareThis',
    'description' => 'Choose the widget, button family, and services for using ShareThis to share content online.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('sharethis_settings_form'),
    'access arguments' => array('administer sharethis'),
    'file' => 'sharethis.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function sharethis_theme($existing, $type, $theme, $path) {
  return array(
    'sharethis_widget' => array(
      'variables' => array(
        'url' => NULL,
        'title' => NULL,
        'classes' => array(),
        'options' => array(),
      ),
      'file' => 'sharethis.theme.inc',
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function sharethis_node_view($node, $view_mode, $langcode) {
  // Don't display on certain view modes.
  switch ($view_mode) {
    case 'search_result':
    case 'search_index':
    case 'rss':
      return;
  }

  $config = config('sharethis.settings');
  $enabled_types = $config->get('node_types');

  if (isset($enabled_types[$node->type]) && $enabled_types[$node->type] === $node->type) {
    $variables = array(
      'property' => $config->get('property'),
      'product' => $config->get('product'),
    );
    $node->content['sharethis'] = array(
      '#type' => 'markup',
      '#markup' => theme('sharethis_widget', $variables),
    );
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function sharethis_field_extra_fields() {
  $extra = array();
  $config = config('sharethis.settings');
  $enabled_types = $config->get('node_types');

  $entity_info = entity_get_info('node');
  foreach ($entity_info['bundles'] as $bundle => $bundle_info) {
    if (isset($enabled_types[$bundle]) && ($enabled_types[$bundle] == $bundle)) {
      $extra['node'][$bundle]['display'] = array(
        'sharethis' => array(
          'label' => t('ShareThis'),
          'description' => t('ShareThis social sharing buttons'),
          'weight' => intval($config->get('sharethis_weight')),
        ),
      );
    }
  }

  return $extra;
}

/**
 * Implements hook_block_info().
 */
function sharethis_block_info() {
  $blocks['sharethis_block'] = array(
    'info' => t('ShareThis buttons'),
    'description' => t('Provides social icons with links for easily sharing content.'),
    'cache' => BACKDROP_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements of hook_block_view().
 */
function sharethis_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'sharethis_block':
      $block['content'] = sharethis_block_contents();
      break;
  }
  return $block;
}

/**
 * Block view callback.
 *
 * @return string
 */
function sharethis_block_contents() {
  $config = config('sharethis.settings');
  $variables = array(
    'property' => $config->get('property'),
    'product' => $config->get('product'),
  );

  return theme('sharethis_widget', $variables);
}

/**
 * Implements hook_comment_view().
 */
function sharethis_comment_view($comment, $view_mode, $langcode) {
  if (config_get('sharethis.settings', 'comments')) {
    $config = config('sharethis.settings');
    $variables = array(
      'property' => $config->get('property'),
      'product' => $config->get('product'),
    );

    $comment->content['sharethis'] = array(
      '#type' => 'markup',
      '#markup' => theme('sharethis_widget', $variables),
    );
  }
}

/**
 * Implements hook_contextual_links_view_alter().
 */
function sharethis_contextual_links_view_alter(&$element, $items) {
  // Add the configuration link for the ShareThis settings on the block itself.
  if (isset($element['#element']['#block']->module) &&
    $element['#element']['#block']->module == 'sharethis' &&
    $element['#element']['#block']->delta == 'sharethis_block' &&
    user_access('access administration pages')) {

    $element['#links']['sharethis-configure'] = array(
      'title' => t('Configure ShareThis'),
      'href' => 'admin/config/services/sharethis',
    );
  }
}

/**
 * Implements hook_views_api().
 */
function sharethis_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'sharethis') . '/views',
  );
}
