<?php

  /**
   *
   * hook_form_alter()
   */

  function simplo_site_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'sites_node_form'){
      $form['#validate'][] = 'simplo_site_custom_validate';
    }
  }

  /**
   *
   * Custom sites node form validation
   */

  function simplo_site_custom_validate(&$form, &$form_state) {
    $site_name = $form_state['input']['field_sites_site_name']['und'][0]['value'];
    if ($site_name !== trim($site_name) || preg_match('/^[a-z0-9\-]{1,30}$/', $sitename) !== false) {
      form_set_error('field_sites_site_name',t('You may only use lowercase letters, numbers and dashes in your site name. No spaces allowed.!') );
    }
  }