<?php

  function simplo_events_node_presave($node) {
    if ($node->type == 'simplo_session') {
      backdrop_set_message($message = "This is the Simplo Events Module", $type = 'status', $repeat = TRUE);

      if (isset($node->field_time_slot['und'][0]['nid'])) {

        $old_time = $node->original->field_time_slot['und'][0]['nid'];
        $new_time = $node->field_time_slot['und'][0]['nid'];

        // release previous time slot
        if (isset($node->original->field_time_slot['und'][0]['nid'])) {
//          backdrop_set_message($message = "release previous time slot.", $type = 'status', $repeat = TRUE);
          $time_slot = node_load($old_time);
          $time_slot->field_slot_taken['und'][0]['value'] = 0;
          $time_slot->save();
        }
//        backdrop_set_message($message = "claim open time slot.  ", $type = 'status', $repeat = TRUE);

        // claim open time slot
        $time_slot = node_load($new_time);
        $time_slot->field_slot_taken['und'][0]['value'] = 1;
        $time_slot->save();

//        backdrop_set_message($message = $old_time . " changed to " . $new_time, $type = 'status', $repeat = TRUE);
//        backdrop_set_message($message = "Updating scheduled time", $type = 'status', $repeat = TRUE);
        $node->field_scheduled_time['und'][0]['nid'] = $new_time;
      }
    }
  }





