<?php

  function simplo_events_node_presave($node) {
    if ($node->type == 'simplo_session') {

      // release previous time slot
      $tid = $node->original->field_time_slot['und'][0]['target_id'];
      $time_slot = node_load($tid);
      $time_slot->field_slot_taken['und'][0] =  FALSE;
      $time_slot->save();

      // claim open time slot
      $tid = $node->field_time_slot['und'][0]['target_id'];
      $time_slot = node_load($tid);
      $time_slot->field_slot_taken['und'][0] = TRUE;
      $time_slot->save();
    }
  }


