<?php

function config_batch_import_menu() {

  $items['admin/config/development/configuration/batch'] = array(
    'title' => 'Batch Import',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('config_batch_import_import_recipe_form'),
    'access arguments' => array('synchronize configuration'),
    'file' => 'config_batch_import.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );
//  $items['admin/config/development/configuration/recipe/import'] = array(
//    'title' => 'Import',
//    'type' => MENU_DEFAULT_LOCAL_TASK,
//  );
  return $items;
}